name: Build

on:
  push:
    branches: [ master, develop ]

jobs:
  build_api_image:
    name: Build API Docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build image
        uses: docker/build-push-action@v1
        with:
          dockerfile: ./Dockerfile-api
          target: prod
          push: true
          tags: etimo/etimo-id/etimo-id-api:latest

  build_web_image:
    name: Build Web Docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build image
        uses: docker/build-push-action@v1
        with:
          dockerfile: ./Dockerfile-web
          target: prod
          push: true
          tags: etimo/etimo-id/etimo-id-web:latest
