name: Build

on:
  push:
    branches: [ master, develop ]

jobs:
  build_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build image
        uses: docker/build-push-action@v1
        with:
          dockerfile: ./Dockerfile
          target: prod
          push: false
