name: Publish

on:
  release:
    types: [ published ]

jobs:
  publish_image:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build & push image
        uses: docker/build-push-action@v1
        with:
          dockerfile: ./Dockerfile
          target: prod
          tag_with_ref: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: etimo/etimo-id/etimo-id
