name: Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      SOLUTION_FILE: etimo-id.sln
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - run: dotnet restore $SOLUTION_FILE
      - name: dotnet build
        run: dotnet build $SOLUTION_FILE --configuration Release --no-restore
      - name: dotnet test
        run: dotnet test $SOLUTION_FILE --configuration Release --no-restore --no-build --collect:"XPlat Code Coverage" --results-directory ./results
      - name: codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: "**/coverage.cobertura.xml"
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
